spring.application.name=Audio Lightning

spring.datasource.url=jdbc:postgresql://localhost:5432/audio_platform
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=false

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

server.error.whitelabel.enabled=false

app.storage.audio-path=storage/audio
app.storage.max-file-size-bytes=52428800
app.bootstrap.admin-username=admin
app.bootstrap.admin-email=admin@local
app.bootstrap.admin-password=admin123
